language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt -U
  - pip install python-coveralls
  - pip install coverage       # Add me to install coverage.py
  - pip install nose           # Add me to install nose
  - pip install pytest
  # - python setup.py install
# command to run tests
script:
#  - cd tests && pytest
  - python setup.py install
  - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  - coveralls
