language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt -U
  - pip install pytest
# command to run tests
script:
  - cd tests && pytest
